### ISSUE TITLE
Feature Request: Save new-reply drafts

### ISSUE THREAD

**Issue by audax** [spuxx1701/potber-client#112]
I use potber as a PWA on android. When I start writing a new reply and switch to a different application, android sometimes kills the process and when I switch back to the PWA, it reloads to an empty new-reply page for the correct thread, but my draft is lost.

Proposed solution: Save the state of the new-reply in local storage and restore it after a cold start if the active page is a new-reply page.

**Comment by spuxx1701** [comment]
Imo, localStorage is not the correct tool for this. I wouldn't mind using sessionStorage, but that wouldn't solve the immediate issue. I've never encountered the PWA clearing its state when I switch to another application. It appears to do so only after longer periods of inactivity. Has this happened more often?

**Comment by spuxx1701** [comment]
I'll close this for now as it's currently not planned. Letting the OS/Browser handle whether to keep or lose the application's state seems like the best solution to me.
