### ISSUE TITLE
Improve Desktop layout

### ISSUE THREAD

**Issue by spuxx1701** [spuxx1701/potber-client#136]
Users are unhappy with the Desktop layout. Things they've mentioned:

- Keep layout similar to mobile with two nav bars
- Optimize space, margins and sizes

**Comment by stehefan** [comment]
Moin. Würd mich da mal drum kümmern - MR oder hier direkt im Projekt? :-) 

~noff

**Comment by spuxx1701** [comment]
Moin @stehefan ! Gerne MR. :)

**Comment by spuxx1701** [comment]
I did most improvements I was planning to do. Imo, the desktop mode is quite usable at this point and I switched over completely. Closing.
