### ISSUE TITLE
 Bookmark page always starts at the bottom since i have saved posts

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#159]
Since i used the "save post" function, every time i browse the bookmark page it starts at the very bottom. i would have assumed it would start on the top as before.

**Comment by spuxx1701** [comment]
Cannot reproduce. Let me know if this is still an issue on 1.8.1 (will release soon), otherwise I'll close this

**Comment by Flitzpiepe42** [comment]
Bin gerade auf 1.8, hatte ich es sporadisch. Was dort aber reproduzierbar geht:

- Start im pOT
- Lesezeichen checken, sollten an Pos1 orientiert sein
- Zurück über Haus-Symbol ins pOT navigieren, ans Ende der ersten Seite scrollen
- Lesezeichen aufrufen: Man ist irgendwo mittig in den Lesezeichen (ich hab um die 60)

wie üblich:
Safari
iOS 16.6
iPhone SE

**Comment by Flitzpiepe42** [comment]
haha, ich habs 🫥 

es ist ziemlich dumm zu reproduzieren (und nachdem ichs nun versteh auch klar warum mir das so oft passiert - navigiere häufig über Lesezeichen, die dann schon nen paar Posts aufgetürmt haben).

- im pOT starten.
- einen Thread öffnen mit möglichst vielen Posts
- hochscrollen über nen paar Screenhöhen, wieder zum Ende scrollen
- Lesezeichen öffnen, man befindet sich am Boden.

Im Übrigen ist das auch bei den PMs so, die sind auch "gescrollt"

**Comment by spuxx1701** [comment]
Hmm könnte ein safari issue sein, ich krieg's auf Chrome grad nicht reproduziert

**Comment by Flitzpiepe42** [comment]
well - kannste schließen, mit 1.9.1 nicht mehr nachvollziehbar
