### ISSUE TITLE
Editing a post is not possible when post body is too small

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#165]
When a post body (content/text) is to small, the context menu (three dots) cannot be rendered completly in the usable area - editing the post is not possible.

![IMG_1549](https://github.com/spuxx1701/potber-client/assets/6689231/e6bd1242-983e-4c15-bbdc-ec2bf4ec2ded)

potber 1.7, iOS 16.5.1, iPhone SE

**Comment by spuxx1701** [comment]
Probier mal PWA. Auf dem SE bleibt ja echt nicht mehr viel Platz übrig in Safari. Der eigentliche Inhalt ist ja mini.😄

**Comment by Flitzpiepe42** [comment]
muss ich beizeiten nochmal nachstellen, soweit gings in der PWA erstmal

**Comment by spuxx1701** [comment]
ich schließ den mal, gerne wiedereröffnen
