### ISSUE TITLE
unterster gespeicherter Post lässt sich nicht löschen

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#171]
Der unterstes gespeicherte Post lässt sich in der PWA (iphone SE, 16.6) nicht löschen, da das Kontextmenü nach unten rutscht und verdeckt wird.

**Comment by Flitzpiepe42** [comment]
![image](https://github.com/spuxx1701/potber-client/assets/6689231/44169a08-ae10-4b4f-b269-c6e2f2dda406)

**Comment by spuxx1701** [comment]
fixed in 30c3843ee8b34c392bb5ebbe92c74689761b7421
