### ISSUE TITLE
Navigationsleiste an falscher Position nach "Zurück"

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#173]
![image](https://github.com/spuxx1701/potber-client/assets/6689231/4310d2b4-6e0a-4217-b0a6-bddda721a72f)

Getestet (reproduzierbar): Vom CS-GO-Thread mit dem potber-internen Zurück-Pfeil aus der Navbar -> Navigationsleiste ist verschoben.

PWA
IPhone SE
iOS 16.6
Safari

**Comment by spuxx1701** [comment]
safari doing safari things 
![MrwMyCoworkerTriesToConvinceMeItTakes18mosToGiveBirthToTwinsGIF](https://github.com/spuxx1701/potber-client/assets/39671641/8411fb96-3231-4a45-ae09-18f8ad9756a7)

**Comment by spuxx1701** [comment]
Hmm, ich kann das aufm iPhone nicht reproduzieren leider

**Comment by spuxx1701** [comment]
Betrifft das noch andere Threads?

**Comment by Flitzpiepe42** [comment]
Kann es selbst dort nicht mehr reproduzieren, andere random geöffnete Threads auch nicht (war mir zuvor auch nicht aufgefallen)

**Comment by spuxx1701** [comment]
Dann schließ ich mal, gerne wiedereröffnen
