### ISSUE TITLE
Smileys in PMs werden nicht geparst

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#177]
![image](https://github.com/spuxx1701/potber-client/assets/6689231/aa6f6b24-c95d-4e48-86d4-08e19c4cf751)

die Smileys in PMs werden nicht geparst.

iOS 16.6
iPhone SE
Safari

**Comment by spuxx1701** [comment]
duplicate of 94126408f8ccdf89fb80a141f89b8b062db87155, but thanks anyway :)

**Comment by Flitzpiepe42** [comment]
oh, sry
