### ISSUE TITLE
Blinkender Header im Optionsmenü

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#178]
![image](https://github.com/spuxx1701/potber-client/assets/6689231/ba30ed17-33eb-4261-807f-91159843835c)

Wenn man die Benderoption klickt (egal ob Menü auf oder zu) verschwindet kurz die Überschrift ...

**Comment by spuxx1701** [comment]
safari 🙃

**Comment by Flitzpiepe42** [comment]
fixt in 1.9.1

**Comment by spuxx1701** [comment]
oh toll
