### ISSUE TITLE
[Feature Request]Sprung ins PM-Menü nach Klicken einer PM

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#179]
Wenn man eine PM im "Drei-Balken"-Menü anklickt erwarte ich, auf die PM zu springen. Das passiert zwar im Hintergrund, aber das Menü schließt sich nicht wie es das bei Lesezeichen tut.

**Comment by spuxx1701** [comment]
fixed in a24cf6c69af3627f5366d7dfaa4be40ea1bb5897
