### ISSUE TITLE
Kontextmenüs von Posts abgeschnitten

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#209]
Vermutlich weils nächste Objekt gerendert wird fehlt ein Teil vom Menü. Nur bei diesem kurzen Post, bei längeren (z.B. der darunter) geht es.

https://forum.mods.de//thread.php?TID=219496&PID=1250067430
![image](https://github.com/spuxx1701/potber-client/assets/6689231/368c96d3-0540-4b40-9c7b-555e044af17e)

iPhone SE
iOS 17.1.2

**Comment by spuxx1701** [comment]
fixed in 681f5ebc4c1cbfe7a0a3d42f8b2f5abbbec226cd
