### ISSUE TITLE
Post-Direktlink fehlerhaft

### ISSUE THREAD

**Issue by Armag3ddon** [spuxx1701/potber-client#222]
Direktlinks, welche über die Datums-/Uhrzeitszeile kopiert werden können, sind fehlerhaft gestaltet:

Aus potber heraus: https://forum.mods.de//thread.php?TID=219545&PID=1250099639

- Doppelslash vor thread.php
- html Anker fehlt

Vergleich zum regulären Link:
https://forum.mods.de/thread.php?TID=219545&PID=1250099639#reply_1250099639

**Comment by spuxx1701** [comment]
fixed in b6c956ad7c4dbde5afc88ff6b30823f762b03476
