### ISSUE TITLE
Textbox abgeschnitten bei langen Quotes

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#223]
Endlich komm ich mal dazu - bei sehr großen Quotes kann ich das Ende der Textbox (in dem ich den Post verfasse) nicht erreichen.
Ich kann die Textbox scrollen (bei der Scrollanimation sehe ich auch das Ende), ich kann das gesamte Fenster scrollen, also auch weiter runter zu den letzten Posts. Nur ist die Scrollposition der Textbox nicht passend zu dem Ausschnitt, in dem es angezeigt wird.

Wenn ich den Cursor in der Textbox setze und damit runterscrolle, scrollt der unendlich durch den Thread ...

IPhone SE
iOS 17.2.1

Zitierter Post:

https://forum.mods.de/thread.php?TID=215025&PID=1250103383#reply_1250103383

![image](https://github.com/spuxx1701/potber-client/assets/6689231/2a78d448-30d8-4465-9451-3b3347cff172)

**Comment by spuxx1701** [comment]
Besteht das Problem noch bei 1.18.x?

**Comment by Flitzpiepe42** [comment]
Ja, gestern erst wieder gehabt, laut App 1.18.1

**Comment by spuxx1701** [comment]
@Flitzpiepe42 ist das seit 1.20.0 eigentlich noch aktuell?

**Comment by Flitzpiepe42** [comment]
ich weiß nicht ob es die Version war, aber nach ner Diskussion im pOt hattest du da nen Fix gezaubert, ist obsolet
