### ISSUE TITLE
Abdunkeln-Effekt geht nicht

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#227]
potber 1.18.0
iOS 17.2.1
iPhone SE

In den Einstellungen ist "Gelesene Posts abdunkeln" auf "Ja", dennoch wirkt es nicht.

**Comment by Flitzpiepe42** [comment]
Verknüpfung vom Homebildschirm gelöscht, Safari beendet, auch über Einstellungen-Safari die Webseitendaten gelöscht - hat nicht geholfen

**Comment by spuxx1701** [comment]
@Flitzpiepe42 ist das auch noch aktuell?

**Comment by Flitzpiepe42** [comment]
yes

**Comment by Flitzpiepe42** [comment]
auch nach dem Neuinstallieren, egal ob potber oder mods.de-stil

**Comment by spuxx1701** [comment]
fixed in 754a52ae35d15c448b984253fc531e4a2203eec2
