### ISSUE TITLE
Add possibility to update bookmark manually

### ISSUE THREAD

**Issue by Phillinger** [spuxx1701/potber-client#25]
Please add the option to the kebab menu of each posting to be able to set/update the bookmark on it.

**Comment by spuxx1701** [comment]
Diese Option? 😅
![image](https://user-images.githubusercontent.com/39671641/218980019-6fe27c19-63bd-4874-932f-ea603bb80ad4.png)

**Comment by Phillinger** [comment]
Ja! :D War die echt schon da? 'schwör, die war nicht da, als ich zuletzt test.potber nutzen konnte.
