### ISSUE TITLE
Fehler bei URL-Eingabe: verschobener Fokus

### ISSUE THREAD

**Issue by Flitzpiepe42** [spuxx1701/potber-client#271]
Wenn man eine Antwort schreibt und dabei eine URL einfügt ist der Fokus der Textbox verändert und die Eingabeleiste mit Smileys und Co muss erst wieder erscrollt werden.

Vor dem URL-Einfügen:
![image](https://github.com/spuxx1701/potber-client/assets/6689231/a30ae1b7-eed7-41df-8a4c-1eeb6ad7634b)

Nach dem URL-Einfügen:
![image](https://github.com/spuxx1701/potber-client/assets/6689231/d9ede372-02cc-4154-ab27-148aa2096650)

eingefügt wurde folgende Url:
"https://github.com/spuxx1701/potber-client/issues/270"

Text war "test"

**Comment by spuxx1701** [comment]
Auf Chrome/Firefox nicht reproduzierbar

**Comment by Flitzpiepe42** [comment]
habs gerade getestet, in Safari unter 1.20.1 leider noch aktuell

**Comment by herrkris** [comment]
Das Problem scheint das Onscreen Keyboard bei Safari zu sein, wenn ein Input-Feld fokussiert wird. Dadurch wird gescrollt, aber nicht wieder die alte Position beim `blur` hergestellt.

https://github.com/user-attachments/assets/3cfd0bc7-3c86-4821-9ca1-3d3c63263948
