### ISSUE TITLE
Ausgewähltes Post-Icon wird nicht angezeigt

### ISSUE THREAD

**Issue by Almischalmi** [spuxx1701/potber-client#275]
Nach Auswahl des Post-Icons, wird dieses leider nicht angezeigt. Statt des vorherigen Platzhalter-Smileys ist das Feld dann leer. Gepostet wird es dann aber.

![D8ACAA52-AF93-4FAD-BA89-58749AC82AD9](https://github.com/user-attachments/assets/5979d885-1883-4959-be96-9f7dbd95e53b)

iOS 17.5.1
Safari

**Comment by spuxx1701** [comment]
Kann ich auf Chrome und Firefox nicht nachstellen. Betrifft das Problem alle icons oder nur ein bestimmtes Icon?

**Comment by Almischalmi** [comment]
Alle Icons

**Comment by herrkris** [comment]
Mit #318 sollte der Bug behoben sein.

**Comment by spuxx1701** [comment]
Danke!
