### ISSUE TITLE
Sprung zu ungelesenen Posts landet zu weit oben

### ISSUE THREAD

**Issue by Almischalmi** [spuxx1701/potber-client#276]
Nach Klick auf ein Lesezeichen mit ungelesenen Posts lande ich immer ein paar Posts drüber und muss dann erst zum Umbruch runterscrollen. Statisch und dynamisches Seitenende macht keinen Unterschied.

iOS 17.5.1
Safari

**Comment by spuxx1701** [comment]
Bekanntes Problem, entsteht durch viele nachladende Inhalte auf der Seite wie z.B. Bilder oder videos
