### ISSUE TITLE
Feature Request: Ability to hide users' posts

### ISSUE THREAD

**Issue by iryda** [spuxx1701/potber-client#291]
Providing a way to block some users' posts (and quotes of their posts) would be very appreciated.

A "soft" blocking function would be preferable to hiding the posts/quotes completely (like implemented in the simple userscript showcased in discord, for example: by blurring them and allowing to un-/reblur them on click/tap), as the latter would probably make threads be a bit confusing at times ^^

[hier das „schöne Augen machen und mit den Wimpern klimpern“ hindenken plz!]

**Comment by spuxx1701** [comment]
@iryda Bei zitierten Posts, sollte dann der gesamte zitierende Post versteckt werden oder nur das Zitat?

**Comment by iryda** [comment]
Im userscript zumindest hatte ich's mit „nur das Zitat” gelöst; dachte mir, dass damit ja meist das „Relevanteste“ ausreichend abgedeckt sein sollte, und die zitierenden Posts an sich ja eher okayish wären meist. Hoffentlich?
_Bisher_ scheint das zu passen, aber ich hab das jetzt auch erst seit zwei Stunden oder so in Benutzung /o\

**Comment by spuxx1701** [comment]
Added in 29bcf1de12c9878fb533a65d6d9467ad1427387d
