### ISSUE TITLE
Some youtube-iframes do not work

### ISSUE THREAD

**Issue by Phillinger** [spuxx1701/potber-client#32]
Example for not working youtube-iframe:
https://test.potber.de/thread?TID=219308&PID=1249839178#reply_1249839178

Example for working youtube-iframe:
https://test.potber.de/thread?TID=219308&PID=1249841051#reply_1249841051

Problem seems to be the [parsing](https://github.com/spuxx1701/potber-client/blob/7c8f79311637863b53b7e5f06991d8740659e753/app/services/content-parser.ts#L142) of the video url. See the resulting iframes:

not working:
`<iframe class="youtube-player" type="text/html" src="https://www.youtube.com/embed/watch?v=eDB5jgnODYY?&origin=https://test.potber.de" frameborder="0"></iframe>`

working:
`<iframe class="youtube-player" type="text/html" src="https://www.youtube.com/embed/watch?v=xAF_X4ssRw4&list=RDxAF_X4ssRw4&start_radio=1&ab_channel=AndreAntunes?&origin=https://test.potber.de" frameborder="0"></iframe>`

Probably already covered with #28 - but this is more specific. ;)

**Comment by spuxx1701** [comment]
This *should* be fixed in fc20d068331c76fbcc7bb930d2b13cb10389211b. A quick test didn't show any youtube videos that didn't get parsed properly for me, but it's possible that there are still some edges that the parser doesn't recognize. If you come across any, let me know. :)
