### ISSUE TITLE
Smilies deaktivieren ohne Funktion

### ISSUE THREAD

**Issue by Almischalmi** [spuxx1701/potber-client#332]
Siehe Titel, ich  aktiviere “Smilies deaktivieren” vorm posten, es wird aber ein Smiley statt Ascii gepostet. 

Safari, iOS 18.1.1

**Comment by spuxx1701** [comment]
Das ist eine Limitation der Foren-API. Im Forum selbst sibd smilies tatsächlich dealtiviert (prüfe das gerne für deinen Post).

Das Forum verrät über die API aber nicht, dass Smilies für einen bestimmten Post deaktiviert werden. Dasselbe gilt auch für die anderen Flags.
