### ISSUE TITLE
Pictures are not displayed if URL contains special chars

### ISSUE THREAD

**Issue by Phillinger** [spuxx1701/potber-client#58]
Error seems to occure when picture url contains special characters.

_forum.mods.de (working):_
https://forum.mods.de/bb//thread.php?TID=219333&PID=1249853907#reply_1249853907
`https://p6.focus.de/img/fotos/id_603700/wissen-asterix-der-gallier.jpg?im=Crop%3D%280%2C149%2C1500%2C750%29%3BResize%3D%28800%2C400%29&impolicy=perceptual&quality=medium&hash=22ce3214719cb95fca1a00315c6aae7890a2e0dfa967b787454cc2a00b11bcd5`

_potber (does not work):_
https://potber.de/thread/?TID=219333&PID=1249853907#reply_1249853907
`https://p6.focus.de/img/fotos/id_603700/wissen-asterix-der-gallier.jpg?im=Crop=(0,149,1500,750);Resize=(800,400)&impolicy=perceptual&quality=medium&hash=22ce3214719cb95fca1a00315c6aae7890a2e0dfa967b787454cc2a00b11bcd5`

**Comment by spuxx1701** [comment]
@Phillinger The image now renders for me on potber. Could have been fixed via one of the encoding/decoding changes I made API-side. Can I close this?

**Comment by Phillinger** [comment]
> @Phillinger The image now renders for me on potber. Could have been fixed via one of the encoding/decoding changes I made API-side. Can I close this?

I'm totally fine with that - go ahead. 👍
