### ISSUE TITLE
Some avatars do not load properly

### ISSUE THREAD

**Issue by spuxx1701** [spuxx1701/potber-client#9]

**Comment by Phillinger** [comment]
### Not loading properly: ###
#### forum.mods.de: ####
`<img src="avatare/oldb/shooter.gif" alt="shooter" class="av " border="0">`

#### test.potber.de: ####
`<img src="https://forum.mods.de/bb/atare/oldb/shooter.gif" alt="☉‿⚆​​" aria-hidden="true">`

Notice the missing "av" in the url's "avatare". Seems always to be a problem, if the avatar is stored under "avatare/oldb" without leading slash or dot-slash.



### Loading properly: ###
#### forum.mods.de: ####
`<img src="./avatare/upload/U59649--lunokl.gif" alt="AUP Lunovis 27.11.2007" class="av " border="0">`
#### test.potber.de: ####
`<img src="https://forum.mods.de/bb/avatare/upload/U59649--lunokl.gif" alt="☉‿⚆​​" aria-hidden="true">`

**Comment by spuxx1701** [comment]
Thanks! ❤
fixed in dc5291d917002c07e3ea34f71b0c719f6c933f52
